# Makefile created by mkmf $Id: mkmf,v 18.0.18.4

SRCROOT = /projects/ees/dhs-crc/mjisan/HBL_V_DEV5/INIT3/boundary_parametric/IRMA/exps/1KM_MICHAEL/objs/



include /projects/ees/dhs-crc/mjisan/HBL_V_DEV5/INIT3/boundary_home/templates/intel_default.mk


.DEFAULT:
	-echo $@ does not exist.
all: /projects/ees/dhs-crc/mjisan/HBL_V_DEV5/INIT3/boundary_parametric/IRMA/exps/1KM_MICHAEL/EXEC/boundary_parametric.exe
SRC =
OBJ =
clean: neat
	-rm -f ./projects/ees/dhs-crc/mjisan/HBL_V_DEV5/INIT3/boundary_parametric/IRMA/exps/1KM_MICHAEL/EXEC/boundary_parametric.exe.cppdefs $(OBJ) /projects/ees/dhs-crc/mjisan/HBL_V_DEV5/INIT3/boundary_parametric/IRMA/exps/1KM_MICHAEL/EXEC/boundary_parametric.exe
neat:
	-rm -f $(TMPFILES)
TAGS: $(SRC)
	etags $(SRC)
tags: $(SRC)
	ctags $(SRC)
/projects/ees/dhs-crc/mjisan/HBL_V_DEV5/INIT3/boundary_parametric/IRMA/exps/1KM_MICHAEL/EXEC/boundary_parametric.exe: $(OBJ) 
	$(LD) $(OBJ) -o /projects/ees/dhs-crc/mjisan/HBL_V_DEV5/INIT3/boundary_parametric/IRMA/exps/1KM_MICHAEL/EXEC/boundary_parametric.exe  $(LDFLAGS)
